version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/data-lake;
      mc version enable local/data-lake;
      echo 'Bucket created and versioning enabled.';
      "

  # pipeline:
  #   build: .
  #   depends_on:
  #     - minio
  #     - minio-init
  #   environment:
  #     AWS_ACCESS_KEY_ID: minioadmin
  #     AWS_SECRET_ACCESS_KEY: minioadmin

  dagster-webserver:
    build: .
    container_name: dagster-webserver
    command: dagster-webserver -h 0.0.0.0 -p 3000 -w /opt/dagster/dagster_home/workspace.yaml
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - dagster-home:/opt/dagster/dagster_home
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      DAGSTER_HOME: /opt/dagster/dagster_home

  dagster-daemon:
    build: .
    container_name: dagster-daemon
    command: dagster-daemon run -w /opt/dagster/dagster_home/workspace.yaml
    restart: unless-stopped
    volumes:
      - dagster-home:/opt/dagster/dagster_home
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      DAGSTER_HOME: /opt/dagster/dagster_home

  dbt:
    build: ./dbt
    container_name: dbt
    volumes:
      - ./dbt:/usr/app/dbt
    working_dir: /usr/app/dbt
    # depends_on:
    #   dagster-webserver:
    #     condition: service_completed_successfully
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    # command: ["sh", "-c", "dbt run && dbt test"]

volumes:
  dagster-home: